ci: test

diff --git a/.github/workflows/update-visual-snapshots.yml b/.github/workflows/update-visual-snapshots.yml
--- a/.github/workflows/update-visual-snapshots.yml
+++ b/.github/workflows/update-visual-snapshots.yml
@@ -31,52 +31,107 @@ jobs:
       - uses: alessbell/pull-request-comment-branch@v2.1.0
         id: comment-branch
 
-      - name: Get sha
-        id: parse-sha
-        continue-on-error: true
-        run: |
-          if [ "${{ steps.comment-branch.outputs.head_owner }}" == "danielleroux" ]; then
-            node ./scripts/update-snapshots.mjs $COMMENT_BODY --sha ${{ steps.comment-branch.outputs.head_sha }} --owner danielleroux
-          else
-            node ./scripts/update-snapshots.mjs $COMMENT_BODY
-          fi
+      # - name: Get sha
+      #   id: parse-sha
+      #   continue-on-error: true
+      #   run: |
+      #     if [ "${{ steps.comment-branch.outputs.head_owner }}" == "danielleroux" ]; then
+      #       node ./scripts/update-snapshots.mjs $COMMENT_BODY --sha ${{ steps.comment-branch.outputs.head_sha }} --owner danielleroux
+      #     else
+      #       node ./scripts/update-snapshots.mjs $COMMENT_BODY
+      #     fi
+      #   env:
+      #     COMMENT_BODY: ${{ github.event.comment.body }}
+      - uses: actions/github-script@v7
+        id: parse-command
+        with:
+          script: |
+            const owner = "${{ steps.comment-branch.outputs.head_owner }}";
+            const body = process.env.COMMENT_BODY;
+
+            const [command, ...commandArgs] = body.split(' ');
+
+            function parseArgs() {
+              const result = {};
+              const arr = commandArgs.map((arg) => {
+                const param = arg.substring(0, arg.indexOf('=')).replace('--', '');
+                const value = arg.substring(arg.indexOf('=') + 1);
+                return {
+                  param,
+                  value,
+                };
+              });
+
+              arr.forEach(({ param, value }) => {
+                result[param] = value;
+              });
+
+              return result;
+            }
+
+            function setOutput(args) {
+              Object.keys(args).forEach((key) => {
+                core.setOutput(key, args[key]);
+              });
+            }
+
+            if (command !== '/snapshot:approve') {
+              throw Error('Invalid command', command);
+            }
+
+            const args = parseArgs();
+
+            if (owner === 'danielleroux') {
+              setOutput(args);
+              return;
+            }
+
+            if (!args['sha']) {
+              throw Error('No sha provided');
+            }
+
+            setOutput(args);
         env:
           COMMENT_BODY: ${{ github.event.comment.body }}
 
-      - name: Comment sha reminder
-        if: steps.parse-sha.outcome == 'failure'
-        uses: peter-evans/create-or-update-comment@v4.0.0
-        with:
-          issue-number: ${{ github.event.issue.number }}
-          body: |
-            Did you forget to add the sha? Please use `/snapshots:approve --sha <sha>`
-
-      - name: Fail job
-        if: steps.parse-sha.outcome == 'failure'
+      - name: DEbug
         run: |
-          exit 1
+          echo ${{ steps.parse-command.outputs }}
 
-      - name: Checkout ref
-        uses: actions/checkout@v4
-        with:
-          ## specify the owner + repository in order to checkout the fork
-          ## for community PRs
-          repository: ${{ steps.comment-branch.outputs.head_owner }}/${{ steps.comment-branch.outputs.head_repo }}
-          ref: ${{ steps.parse-sha.outputs.sha }}
-          fetch-depth: 0
+      # - name: Comment sha reminder
+      #   if: steps.parse-sha.outcome == 'failure'
+      #   uses: peter-evans/create-or-update-comment@v4.0.0
+      #   with:
+      #     issue-number: ${{ github.event.issue.number }}
+      #     body: |
+      #       Did you forget to add the sha? Please use `/snapshots:approve --sha <sha>`
 
-      - uses: ./.github/workflows/actions/turbo
+      # - name: Fail job
+      #   if: steps.parse-sha.outcome == 'failure'
+      #   run: |
+      #     exit 1
 
-      - name: Build
-        run: pnpm build --cache-dir=.turbo --filter @siemens/ix
+      # - name: Checkout ref
+      #   uses: actions/checkout@v4
+      #   with:
+      #     ## specify the owner + repository in order to checkout the fork
+      #     ## for community PRs
+      #     repository: ${{ steps.comment-branch.outputs.head_owner }}/${{ steps.comment-branch.outputs.head_repo }}
+      #     ref: ${{ steps.parse-sha.outputs.sha }}
+      #     fetch-depth: 0
 
-      - name: Visual Regression
-        run: pnpm --filter @siemens/ix visual-regression ${{ steps.parse-sha.outputs.args }} -u
+      # - uses: ./.github/workflows/actions/turbo
 
-      - name: Commit and push changes
-        run: |
-          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
-          git config user.name "github-actions[bot]"
-          git add -A
-          git commit -m "test: update snapshots (by ${{ github.event.sender.login }})"
-          git push
+      # - name: Build
+      #   run: pnpm build --cache-dir=.turbo --filter @siemens/ix
+
+      # - name: Visual Regression
+      #   run: pnpm --filter @siemens/ix visual-regression ${{ steps.parse-sha.outputs.args }} -u
+
+      # - name: Commit and push changes
+      #   run: |
+      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
+      #     git config user.name "github-actions[bot]"
+      #     git add -A
+      #     git commit -m "test: update snapshots (by ${{ github.event.sender.login }})"
+      #     git push
